### ISSUE TITLE
Fautes

### ISSUE THREAD

**Issue by Konosprod** [dantunescost/Hanabi-P-ANDROIDE#5]
Bonjour,

le projet est intéressant. Le rapport est plutôt nice, mais il y a quelques fautes d'orthographe qui gâchent la lecture. Notamment sur des choses essentielles comme le point 3.2.2, à savoir la VuE.

**Comment by Keithdae** [comment]
Bonjour,

Je suis vraiment désolé pour cette erreur dramatique.
